<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE troubleshooting PUBLIC "-//OASIS//DTD DITA Troubleshooting//EN" "troubleshooting.dtd">
<troubleshooting id="trouble_31_3">
    <title>Ошибка вида «Непредвиденная ошибка. Убедитесь в работоспособности Комплекса или
        обратитесь к администратору»</title>
    <troublebody>
        <troubleSolution>
            <cause>
                <title>Причина: ошибки в сервисе поиска уязвимостей</title>
            </cause>
            <remedy>
                <title>Способ устранения</title>
                <responsibleParty>Для устранения затруднения:</responsibleParty>
                <steps>
                    <step>
                        <cmd>Убедитесь, что в логах сервиса <codeph>vulnerability_backend</codeph>
                            нет ошибок, по команде:</cmd>
                        <info>
                            <codeblock id="codeblock_cz3_nrf_yyb">docker logs -f vulnerability_backend</codeblock>
                        </info>
                    </step>
                    <step>
                        <cmd><ph
                                conref="../../reusable/steps/container_errors_references_step.dita#ReusableComponent_hl4_ysd_l1c/ph_jl4_ysd_l1c"
                            /></cmd>
                    </step>
                </steps>
            </remedy>
        </troubleSolution>
    </troublebody>
</troubleshooting>
